# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170410_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conteneur', models.CharField(max_length=300, null=True)),
                ('id_image', models.CharField(max_length=300)),
            ],
        ),
    ]
